name: Build/release

on: push

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.x
      - run: npm ci
      - run: GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run build
